steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - discover-ad-status
      - --source=.
      - --image=us-east4-docker.pkg.dev/quickads-prod/cloud-run-source-deploy/discover-ad-status
      - --region=asia-southeast1
      - --project=quickads-prod
      - --allow-unauthenticated
      - --memory=512Mi
      - --timeout=300s
      - --max-instances=2

options:
  logging: CLOUD_LOGGING_ONLY
